/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nathanielnarofsky.todolist;

public class lgGpioAlert_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected lgGpioAlert_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lgGpioAlert_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(lgGpioAlert_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lgpioJNI.delete_lgGpioAlert_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReport(lgGpioReport_t value) {
    lgpioJNI.lgGpioAlert_t_report_set(swigCPtr, this, lgGpioReport_t.getCPtr(value), value);
  }

  public lgGpioReport_t getReport() {
    long cPtr = lgpioJNI.lgGpioAlert_t_report_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lgGpioReport_t(cPtr, false);
  }

  public void setNfyHandle(int value) {
    lgpioJNI.lgGpioAlert_t_nfyHandle_set(swigCPtr, this, value);
  }

  public int getNfyHandle() {
    return lgpioJNI.lgGpioAlert_t_nfyHandle_get(swigCPtr, this);
  }

  public lgGpioAlert_t() {
    this(lgpioJNI.new_lgGpioAlert_t(), true);
  }

}
