/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nathanielnarofsky.todolist;

public class lgNotify_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected lgNotify_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lgNotify_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(lgNotify_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lgpioJNI.delete_lgNotify_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setState(int value) {
    lgpioJNI.lgNotify_t_state_set(swigCPtr, this, value);
  }

  public int getState() {
    return lgpioJNI.lgNotify_t_state_get(swigCPtr, this);
  }

  public void setFd(int value) {
    lgpioJNI.lgNotify_t_fd_set(swigCPtr, this, value);
  }

  public int getFd() {
    return lgpioJNI.lgNotify_t_fd_get(swigCPtr, this);
  }

  public void setPipe_number(int value) {
    lgpioJNI.lgNotify_t_pipe_number_set(swigCPtr, this, value);
  }

  public int getPipe_number() {
    return lgpioJNI.lgNotify_t_pipe_number_get(swigCPtr, this);
  }

  public void setMax_emits(int value) {
    lgpioJNI.lgNotify_t_max_emits_set(swigCPtr, this, value);
  }

  public int getMax_emits() {
    return lgpioJNI.lgNotify_t_max_emits_get(swigCPtr, this);
  }

  public lgNotify_t() {
    this(lgpioJNI.new_lgNotify_t(), true);
  }

}
