/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nathanielnarofsky.todolist;

public class lgpio implements lgpioConstants {
  public static String lguGetConfigDir() {
    return lgpioJNI.lguGetConfigDir();
  }

  public static void lguSetConfigDir(String dirPath) {
    lgpioJNI.lguSetConfigDir(dirPath);
  }

  public static int lgGpioSetBannedState(int handle, int gpio, int banned) {
    return lgpioJNI.lgGpioSetBannedState(handle, gpio, banned);
  }

  public static int _gpiochip_open(int gpioDev) {
    return lgpioJNI._gpiochip_open(gpioDev);
  }

  public static int _gpiochip_close(int handle) {
    return lgpioJNI._gpiochip_close(handle);
  }

  public static int _gpio_get_chip_info(int handle, lgChipInfo_t chipInfo) {
    return lgpioJNI._gpio_get_chip_info(handle, lgChipInfo_t.getCPtr(chipInfo), chipInfo);
  }

  public static int _gpio_get_line_info(int handle, int gpio, lgLineInfo_t lineInfo) {
    return lgpioJNI._gpio_get_line_info(handle, gpio, lgLineInfo_t.getCPtr(lineInfo), lineInfo);
  }

  public static int _gpio_get_mode(int handle, int gpio) {
    return lgpioJNI._gpio_get_mode(handle, gpio);
  }

  public static int lgGpioSetUser(int handle, String gpiouser) {
    return lgpioJNI.lgGpioSetUser(handle, gpiouser);
  }

  public static int _gpio_claim_input(int handle, int lFlags, int gpio) {
    return lgpioJNI._gpio_claim_input(handle, lFlags, gpio);
  }

  public static int _gpio_claim_output(int handle, int lFlags, int gpio, int level) {
    return lgpioJNI._gpio_claim_output(handle, lFlags, gpio, level);
  }

  public static int _gpio_claim_alert(int handle, int lFlags, int eFlags, int gpio, int nfyHandle) {
    return lgpioJNI._gpio_claim_alert(handle, lFlags, eFlags, gpio, nfyHandle);
  }

  public static int _gpio_free(int handle, int gpio) {
    return lgpioJNI._gpio_free(handle, gpio);
  }

  public static int _group_claim_input(int handle, int lFlags, int count, SWIGTYPE_p_int gpios) {
    return lgpioJNI._group_claim_input(handle, lFlags, count, SWIGTYPE_p_int.getCPtr(gpios));
  }

  public static int _group_claim_output(int handle, int lFlags, int count, SWIGTYPE_p_int gpios, SWIGTYPE_p_int levels) {
    return lgpioJNI._group_claim_output(handle, lFlags, count, SWIGTYPE_p_int.getCPtr(gpios), SWIGTYPE_p_int.getCPtr(levels));
  }

  public static int _group_free(int handle, int gpio) {
    return lgpioJNI._group_free(handle, gpio);
  }

  public static int _gpio_read(int handle, int gpio) {
    return lgpioJNI._gpio_read(handle, gpio);
  }

  public static int _gpio_write(int handle, int gpio, int level) {
    return lgpioJNI._gpio_write(handle, gpio, level);
  }

  public static int _group_read(int handle, int gpio, SWIGTYPE_p_unsigned_long_long groupBits) {
    return lgpioJNI._group_read(handle, gpio, SWIGTYPE_p_unsigned_long_long.getCPtr(groupBits));
  }

  public static int _group_write(int handle, int gpio, java.math.BigInteger groupBits, java.math.BigInteger groupMask) {
    return lgpioJNI._group_write(handle, gpio, groupBits, groupMask);
  }

  public static int _tx_pulse(int handle, int gpio, int pulseOn, int pulseOff, int pulseOffset, int pulseCycles) {
    return lgpioJNI._tx_pulse(handle, gpio, pulseOn, pulseOff, pulseOffset, pulseCycles);
  }

  public static int _tx_pwm(int handle, int gpio, float pwmFrequency, float pwmDutyCycle, int pwmOffset, int pwmCycles) {
    return lgpioJNI._tx_pwm(handle, gpio, pwmFrequency, pwmDutyCycle, pwmOffset, pwmCycles);
  }

  public static int _tx_servo(int handle, int gpio, int pulseWidth, int servoFrequency, int servoOffset, int servoCycles) {
    return lgpioJNI._tx_servo(handle, gpio, pulseWidth, servoFrequency, servoOffset, servoCycles);
  }

  public static int _tx_wave(int handle, int gpio, int count, lgPulse_t pulses) {
    return lgpioJNI._tx_wave(handle, gpio, count, lgPulse_t.getCPtr(pulses), pulses);
  }

  public static int _tx_busy(int handle, int gpio, int kind) {
    return lgpioJNI._tx_busy(handle, gpio, kind);
  }

  public static int _tx_room(int handle, int gpio, int kind) {
    return lgpioJNI._tx_room(handle, gpio, kind);
  }

  public static int _gpio_set_debounce_micros(int handle, int gpio, int debounce_us) {
    return lgpioJNI._gpio_set_debounce_micros(handle, gpio, debounce_us);
  }

  public static int _gpio_set_watchdog_micros(int handle, int gpio, int watchdog_us) {
    return lgpioJNI._gpio_set_watchdog_micros(handle, gpio, watchdog_us);
  }

  public static int lgGpioSetAlertsFunc(int handle, int gpio, SWIGTYPE_p_f_int_p_struct_lgGpioAlert_s_p_void__void cbf, SWIGTYPE_p_void userdata) {
    return lgpioJNI.lgGpioSetAlertsFunc(handle, gpio, SWIGTYPE_p_f_int_p_struct_lgGpioAlert_s_p_void__void.getCPtr(cbf), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static void lgGpioSetSamplesFunc(SWIGTYPE_p_f_int_p_struct_lgGpioAlert_s_p_void__void cbf, SWIGTYPE_p_void userdata) {
    lgpioJNI.lgGpioSetSamplesFunc(SWIGTYPE_p_f_int_p_struct_lgGpioAlert_s_p_void__void.getCPtr(cbf), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static void lgNotifyCloseOrphans(int slot, int fd) {
    lgpioJNI.lgNotifyCloseOrphans(slot, fd);
  }

  public static int lgNotifyOpenWithSize(int pipeSize) {
    return lgpioJNI.lgNotifyOpenWithSize(pipeSize);
  }

  public static int lgNotifyOpenInBand(int fd) {
    return lgpioJNI.lgNotifyOpenInBand(fd);
  }

  public static int _notify_open() {
    return lgpioJNI._notify_open();
  }

  public static int _notify_resume(int handle) {
    return lgpioJNI._notify_resume(handle);
  }

  public static int _notify_pause(int handle) {
    return lgpioJNI._notify_pause(handle);
  }

  public static int _notify_close(int handle) {
    return lgpioJNI._notify_close(handle);
  }

  public static int _i2c_open(int i2cDev, int i2cAddr, int i2cFlags) {
    return lgpioJNI._i2c_open(i2cDev, i2cAddr, i2cFlags);
  }

  public static int _i2c_close(int handle) {
    return lgpioJNI._i2c_close(handle);
  }

  public static int _i2c_write_quick(int handle, int bitVal) {
    return lgpioJNI._i2c_write_quick(handle, bitVal);
  }

  public static int _i2c_write_byte(int handle, int byteVal) {
    return lgpioJNI._i2c_write_byte(handle, byteVal);
  }

  public static int _i2c_read_byte(int handle) {
    return lgpioJNI._i2c_read_byte(handle);
  }

  public static int _i2c_write_byte_data(int handle, int i2cReg, int byteVal) {
    return lgpioJNI._i2c_write_byte_data(handle, i2cReg, byteVal);
  }

  public static int _i2c_WriteWordData(int handle, int i2cReg, int wordVal) {
    return lgpioJNI._i2c_WriteWordData(handle, i2cReg, wordVal);
  }

  public static int _i2c_read_byte_data(int handle, int i2cReg) {
    return lgpioJNI._i2c_read_byte_data(handle, i2cReg);
  }

  public static int _i2c_read_word_data(int handle, int i2cReg) {
    return lgpioJNI._i2c_read_word_data(handle, i2cReg);
  }

  public static int _i2c_process_call(int handle, int i2cReg, int wordVal) {
    return lgpioJNI._i2c_process_call(handle, i2cReg, wordVal);
  }

  public static int _i2c_write_block_data(int handle, int i2cReg, String txBuf, int count) {
    return lgpioJNI._i2c_write_block_data(handle, i2cReg, txBuf, count);
  }

  public static int _i2c_read_block_data(int handle, int i2cReg, String rxBuf) {
    return lgpioJNI._i2c_read_block_data(handle, i2cReg, rxBuf);
  }

  public static int _i2c_block_process_call(int handle, int i2cReg, String ioBuf, int count) {
    return lgpioJNI._i2c_block_process_call(handle, i2cReg, ioBuf, count);
  }

  public static int _i2c_read_i2c_block_data(int handle, int i2cReg, String rxBuf, int count) {
    return lgpioJNI._i2c_read_i2c_block_data(handle, i2cReg, rxBuf, count);
  }

  public static int _i2c_write_i2c_block_data(int handle, int i2cReg, String txBuf, int count) {
    return lgpioJNI._i2c_write_i2c_block_data(handle, i2cReg, txBuf, count);
  }

  public static int _i2c_read_device(int handle, String rxBuf, int count) {
    return lgpioJNI._i2c_read_device(handle, rxBuf, count);
  }

  public static int _i2c_write_device(int handle, String txBuf, int count) {
    return lgpioJNI._i2c_write_device(handle, txBuf, count);
  }

  public static int lgI2cSegments(int handle, lgI2cMsg_t segs, int count) {
    return lgpioJNI.lgI2cSegments(handle, lgI2cMsg_t.getCPtr(segs), segs, count);
  }

  public static int _i2c_zip(int handle, String txBuf, int txCount, String rxBuf, int rxCount) {
    return lgpioJNI._i2c_zip(handle, txBuf, txCount, rxBuf, rxCount);
  }

  public static int _serial_open(String serDev, int serBaud, int serFlags) {
    return lgpioJNI._serial_open(serDev, serBaud, serFlags);
  }

  public static int _serial_close(int handle) {
    return lgpioJNI._serial_close(handle);
  }

  public static int _serial_write_byte(int handle, int byteVal) {
    return lgpioJNI._serial_write_byte(handle, byteVal);
  }

  public static int _serial_read_byte(int handle) {
    return lgpioJNI._serial_read_byte(handle);
  }

  public static int _serial_write(int handle, String txBuf, int count) {
    return lgpioJNI._serial_write(handle, txBuf, count);
  }

  public static int _serial_read(int handle, String rxBuf, int count) {
    return lgpioJNI._serial_read(handle, rxBuf, count);
  }

  public static int _serial_data_available(int handle) {
    return lgpioJNI._serial_data_available(handle);
  }

  public static int _spi_open(int spiDev, int spiChan, int spiBaud, int spiFlags) {
    return lgpioJNI._spi_open(spiDev, spiChan, spiBaud, spiFlags);
  }

  public static int _spi_close(int handle) {
    return lgpioJNI._spi_close(handle);
  }

  public static int _spi_read(int handle, String rxBuf, int count) {
    return lgpioJNI._spi_read(handle, rxBuf, count);
  }

  public static int _spi_write(int handle, String txBuf, int count) {
    return lgpioJNI._spi_write(handle, txBuf, count);
  }

  public static int _spi_xfer(int handle, String txBuf, String rxBuf, int count) {
    return lgpioJNI._spi_xfer(handle, txBuf, rxBuf, count);
  }

  public static SWIGTYPE_p_pthread_t lgThreadStart(SWIGTYPE_p_f_p_void__p_void f, SWIGTYPE_p_void userdata) {
    long cPtr = lgpioJNI.lgThreadStart(SWIGTYPE_p_f_p_void__p_void.getCPtr(f), SWIGTYPE_p_void.getCPtr(userdata));
    return (cPtr == 0) ? null : new SWIGTYPE_p_pthread_t(cPtr, false);
  }

  public static void lgThreadStop(SWIGTYPE_p_pthread_t pth) {
    lgpioJNI.lgThreadStop(SWIGTYPE_p_pthread_t.getCPtr(pth));
  }

  public static java.math.BigInteger lguTimestamp() {
    return lgpioJNI.lguTimestamp();
  }

  public static double lguTime() {
    return lgpioJNI.lguTime();
  }

  public static void lguSleep(double sleepSecs) {
    lgpioJNI.lguSleep(sleepSecs);
  }

  public static int lguSbcName(String rxBuf, int count) {
    return lgpioJNI.lguSbcName(rxBuf, count);
  }

  public static int lguVersion() {
    return lgpioJNI.lguVersion();
  }

  public static int lguGetInternal(int cfgId, SWIGTYPE_p_unsigned_long_long cfgVal) {
    return lgpioJNI.lguGetInternal(cfgId, SWIGTYPE_p_unsigned_long_long.getCPtr(cfgVal));
  }

  public static int lguSetInternal(int cfgId, java.math.BigInteger cfgVal) {
    return lgpioJNI.lguSetInternal(cfgId, cfgVal);
  }

  public static String lguErrorText(int error) {
    return lgpioJNI.lguErrorText(error);
  }

  public static void lguSetWorkDir(String dirPath) {
    lgpioJNI.lguSetWorkDir(dirPath);
  }

  public static String lguGetWorkDir() {
    return lgpioJNI.lguGetWorkDir();
  }

  public static int _i2c_segments(int handle, lgI2cMsg_t segs, int count) {
    return lgpioJNI._i2c_segments(handle, lgI2cMsg_t.getCPtr(segs), segs, count);
  }

  public static int _get_lg_version() {
    return lgpioJNI._get_lg_version();
  }

  public static int _get_internal(int cfgId, SWIGTYPE_p_unsigned_long_long OUTPUT) {
    return lgpioJNI._get_internal(cfgId, SWIGTYPE_p_unsigned_long_long.getCPtr(OUTPUT));
  }

  public static int _set_internal(int cfgId, java.math.BigInteger cfgVal) {
    return lgpioJNI._set_internal(cfgId, cfgVal);
  }

  public static String _error_text(int error) {
    return lgpioJNI._error_text(error);
  }

}
