/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nathanielnarofsky.todolist;

public class lgLineInfo_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected lgLineInfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lgLineInfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(lgLineInfo_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lgpioJNI.delete_lgLineInfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOffset(long value) {
    lgpioJNI.lgLineInfo_t_offset_set(swigCPtr, this, value);
  }

  public long getOffset() {
    return lgpioJNI.lgLineInfo_t_offset_get(swigCPtr, this);
  }

  public void setLFlags(long value) {
    lgpioJNI.lgLineInfo_t_lFlags_set(swigCPtr, this, value);
  }

  public long getLFlags() {
    return lgpioJNI.lgLineInfo_t_lFlags_get(swigCPtr, this);
  }

  public void setName(String value) {
    lgpioJNI.lgLineInfo_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return lgpioJNI.lgLineInfo_t_name_get(swigCPtr, this);
  }

  public void setUser(String value) {
    lgpioJNI.lgLineInfo_t_user_set(swigCPtr, this, value);
  }

  public String getUser() {
    return lgpioJNI.lgLineInfo_t_user_get(swigCPtr, this);
  }

  public lgLineInfo_t() {
    this(lgpioJNI.new_lgLineInfo_t(), true);
  }

}
