/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nathanielnarofsky.todolist;

public class lgChipInfo_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected lgChipInfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lgChipInfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(lgChipInfo_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lgpioJNI.delete_lgChipInfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLines(long value) {
    lgpioJNI.lgChipInfo_t_lines_set(swigCPtr, this, value);
  }

  public long getLines() {
    return lgpioJNI.lgChipInfo_t_lines_get(swigCPtr, this);
  }

  public void setName(String value) {
    lgpioJNI.lgChipInfo_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return lgpioJNI.lgChipInfo_t_name_get(swigCPtr, this);
  }

  public void setLabel(String value) {
    lgpioJNI.lgChipInfo_t_label_set(swigCPtr, this, value);
  }

  public String getLabel() {
    return lgpioJNI.lgChipInfo_t_label_get(swigCPtr, this);
  }

  public lgChipInfo_t() {
    this(lgpioJNI.new_lgChipInfo_t(), true);
  }

}
