/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nathanielnarofsky.todolist;

public class lgI2cMsg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected lgI2cMsg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lgI2cMsg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(lgI2cMsg_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lgpioJNI.delete_lgI2cMsg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAddr(int value) {
    lgpioJNI.lgI2cMsg_t_addr_set(swigCPtr, this, value);
  }

  public int getAddr() {
    return lgpioJNI.lgI2cMsg_t_addr_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    lgpioJNI.lgI2cMsg_t_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return lgpioJNI.lgI2cMsg_t_flags_get(swigCPtr, this);
  }

  public void setLen(int value) {
    lgpioJNI.lgI2cMsg_t_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return lgpioJNI.lgI2cMsg_t_len_get(swigCPtr, this);
  }

  public void setBuf(SWIGTYPE_p_unsigned_char value) {
    lgpioJNI.lgI2cMsg_t_buf_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getBuf() {
    long cPtr = lgpioJNI.lgI2cMsg_t_buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public lgI2cMsg_t() {
    this(lgpioJNI.new_lgI2cMsg_t(), true);
  }

}
