/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nathanielnarofsky.todolist;

public class lgPulse_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected lgPulse_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lgPulse_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(lgPulse_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lgpioJNI.delete_lgPulse_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBits(java.math.BigInteger value) {
    lgpioJNI.lgPulse_t_bits_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getBits() {
    return lgpioJNI.lgPulse_t_bits_get(swigCPtr, this);
  }

  public void setMask(java.math.BigInteger value) {
    lgpioJNI.lgPulse_t_mask_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getMask() {
    return lgpioJNI.lgPulse_t_mask_get(swigCPtr, this);
  }

  public void setDelay(long value) {
    lgpioJNI.lgPulse_t_delay_set(swigCPtr, this, value);
  }

  public long getDelay() {
    return lgpioJNI.lgPulse_t_delay_get(swigCPtr, this);
  }

  public lgPulse_t() {
    this(lgpioJNI.new_lgPulse_t(), true);
  }

}
